theme: jekyll-theme-minimal

permalink: /:categories/:year/:month/:day/:title.html

title:            Main Page        # Site title
name:             Zhisong Wu          # Your name
avatar:           /theme/img/avatar.jpg   # Path to an avatar image

baseurl: "/xsky"

include: ["_pages", "_portfolio"]

defaults:
# Turn the profile sidebar on for all pages by default, except for the
# collections, where it is off and replaced by useful things on the sidebar.
# To override this one a page, use
#    show_profile: false
# to hide the profile.
  -
    scope:
      path: ""
    values:
      show_profile: true
  -
    scope:
      path: "_posts"
    values:
      show_profile: false
      layout: defaults/post
  -
    scope:
      path: "_portfolio"
    values:
      show_profile: false
      layout: defaults/portfolio
  -
    scope:
      path: "_projects"
    values:
      show_profile: false
      layout: defaults/project
  -
    scope:
      path: "list"
    values:
      show_profile: false
      layout: defaults/list